### ISSUE TITLE
Peter Pack Rat

### ISSUE THREAD

**Issue by Swainy101** [d18c7db/atari_system1_fpga#1]
Just getting a blank screen once the core has booted.

**Comment by d18c7db** [comment]
PeterPackRat sort of works, it has an issue with sprites but definitely not black screen. If you get that it's most likely an issue with the roms you have. The simplest way to check that is to drag the roms into MAME's "roms" folder and at a command line in the MAME directory run the verifyroms command and it should show all good.
C:\mame0249b_64bit>mame -verifyroms peterpak
romset peterpak [atarisy1] is good
1 romsets found, 1 were OK.

If all is not good with command above then run this command for the full set of roms needed to run the game and their checksums.
C:\mame0249b_64bit>mame -listroms peterpak

**Comment by d18c7db** [comment]
Actually you're right, there is a black screen with the released rbf. I'm using a later version which doesn't have that particular problem but has other issues which I'm working on.

**Comment by d18c7db** [comment]
Latest release fixes this problem.

**Comment by Swainy101** [comment]
Superb, thank you very much!
