### ISSUE TITLE
Peter Pack Rat jump button.

### ISSUE THREAD

**Issue by Hodor-git** [d18c7db/atari_system1_fpga#2]
Hello.

I've noticed that Peter Pack Rat has jump and throw actions mapped on to the same button. If I am not mistaken, the actual arcade has two buttons, one for jumping and the other for throwing stones.

Thank you very much for your work.

**Comment by JustinRudebaugh** [comment]
You are correct - There are two buttons.  The jump button is a push button on the top of the joystick, and there's two throw buttons on the control panel (both electronically connected to the same input on the System 1 PCB).

**Comment by Hodor-git** [comment]
Thank you for finding it out. I wish it can be fixed any time soon.

**Comment by d18c7db** [comment]
Hey all, yes the issue is there and the fix is super simple, however adding that simple key/joystick button update seems to break the background music in Indiana, most likely due to unmet timing constraints which are a pain to fix. Hope to slowly slowly make some progress. Alternatively I can release a .rbf that allows you to play Peter but has broken Indiana sound potentially generating a new "issue to fix".

**Comment by Hodor-git** [comment]
Don´t worry and take your time. I am not in a hurry at all and the last thing I want is fixing something to break something.

Thanks!

**Comment by d18c7db** [comment]
Latest rbf sovles Peter input control mapping, you need to also get the latest mra files as the ROM layout has changed.

**Comment by MichaelFrankMusic** [comment]
I’m still missing the jump button in the Peter Pack Rat button mapping config, it only allows me to define the Fire button. Using the latest version through Update All

**Comment by d18c7db** [comment]
I think I know what you're talking about now. When you define the buttons though the on-screen menu, you go through right, left, down, up, start, fire, coin. The START button is also your JUMP button. There's nothing I can do about the naming of those buttons, this is a system ("sys") issue not something I can change in the core AFAIK. Try and see, hope that helps.

**Comment by MichaelFrankMusic** [comment]
> I think I know what you're talking about now. When you define the buttons though the on-screen menu, you go through right, left, down, up, start, fire, coin. The START button is also your JUMP button. There's nothing I can do about the naming of those buttons, this is a system ("sys") issue not something I can change in the core AFAIK. Try and see, hope that helps.

Yes that did work, thank you! I somehow never realized those buttons were the same.
