### ISSUE TITLE
Graphic corruption unless you have 128M of SDRAM

### ISSUE THREAD

**Issue by rittwage** [d18c7db/atari_system1_fpga#6]
Even though the cores doesn't need that much RAM, it doesn't work properly with 32M modules.

![20231021_170208](https://github.com/d18c7db/atari_system1_fpga/assets/122463816/da3eedc8-d399-40a8-b251-56a0551a3914)
![20231021_170120](https://github.com/d18c7db/atari_system1_fpga/assets/122463816/cc7ac79d-caa7-4521-bc23-06717f0d69e2)

**Comment by d18c7db** [comment]
These cores only use 4MB of the SDRAM but you are right, when testing with a 32MB module I get the same result.
It's possible that the SDRAM controller needs some tweaks, it was only tested to work with 128MB modules.

**Comment by rittwage** [comment]
Thanks for verifying. I did try on an old 1.1 32M module as well as a 2.2. Same result.

**Comment by d18c7db** [comment]
This issue should be fixed now. It was due to the way the SDRAM address multiplexing was done for the smaller SDRAM chips. Should now work will all sizes.
