### ISSUE TITLE
Control inputs partially not working

### ISSUE THREAD

**Issue by fiermanb** [d18c7db/atari_system1_fpga#8]
For Road Runner (and possibly others too), inputs Up and Down are not registering in-game. Rebinding does not make any difference.

**Comment by loki666** [comment]
how did you fix it ?

**Comment by fiermanb** [comment]
Sorry, I did not fix it, I only made a new issue in the MiSTer main repo, because I think the issue is MiSTer specific.

**Comment by loki666** [comment]
ah ok thanks
